{
    "name": "NN Fund Management",
    "version": "17.0.1.0.0",
    "category": "Accounting",
    "summary": "Fund management foundation for incoming funds, allocations, requisitions, bills, and transfers.",
    "description": "Placeholder manifest for the NN Fund Management custom module.",
    "author": "Author Name",
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "depends": ["base", "mail", "project"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "views/project_views.xml",
        "views/fund_account_views.xml",
        "views/expense_head_views.xml",
        "views/incoming_fund_views.xml",
        "views/fund_allocation_views.xml",
        "views/fund_requisition_views.xml",
        "views/fund_bill_views.xml",
        "views/fund_transfer_views.xml",
        "views/dashboard_views.xml",
        "views/approval_config_views.xml",
        "views/approval_history_views.xml",
        "views/menu_views.xml",
        "data/sequence_data.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
    ],
}
